platform :ios, '9.0'

install! 'cocoapods', :deterministic_uuids => false, :integrate_targets => false

target 'plantaoenfermagem' do
    
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTImage',
    'RCTGeolocation',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    ]
    # Explicitly include Yoga if you are using RN >= 0.42.0
    
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
    pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'
    pod 'react-native-webview', :path => '../node_modules/react-native-webview'
    pod 'react-native-orientation-locker', :path => '../node_modules/react-native-orientation-locker/react-native-orientation-locker.podspec'
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
    pod 'RNI18n', :path => '../node_modules/react-native-i18n'

end

target 'plantaoenfermagem Local' do
    
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTImage',
    'RCTGeolocation',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    ]
    # Explicitly include Yoga if you are using RN >= 0.42.0
    
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
    pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'
    pod 'react-native-webview', :path => '../node_modules/react-native-webview'
    pod 'react-native-orientation-locker', :path => '../node_modules/react-native-orientation-locker/react-native-orientation-locker.podspec'
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
    pod 'RNI18n', :path => '../node_modules/react-native-i18n'
    
end

target 'plantaoenfermagem Internal' do
    
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTImage',
    'RCTGeolocation',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    ]
    # Explicitly include Yoga if you are using RN >= 0.42.0
    
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
    pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'
    pod 'react-native-webview', :path => '../node_modules/react-native-webview'
    pod 'react-native-orientation-locker', :path => '../node_modules/react-native-orientation-locker/react-native-orientation-locker.podspec'
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
    pod 'RNI18n', :path => '../node_modules/react-native-i18n'
    
end

target 'plantaoenfermagem Staging' do
    
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTImage',
    'RCTGeolocation',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    ]
    # Explicitly include Yoga if you are using RN >= 0.42.0
    
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
    pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'
    pod 'react-native-webview', :path => '../node_modules/react-native-webview'
    pod 'react-native-orientation-locker', :path => '../node_modules/react-native-orientation-locker/react-native-orientation-locker.podspec'
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
    pod 'RNI18n', :path => '../node_modules/react-native-i18n'
    
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'react-native-config'
            phase = target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
            phase.shell_script = "cd ../../"\
            " && RNC_ROOT=./node_modules/react-native-config/"\
            " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\
            " && export BUILD_DIR=$RNC_ROOT/ios/ReactNativeConfig"\
            " && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.ruby"
            
            target.build_phases << phase
            target.build_phases.move(phase,0)
        end
        if target.name == "React"
            target.remove_from_project
        end
        if target.name == "yoga"
            target.remove_from_project
        end
    end
end

