export enum Navigation {
  ScheduleScreen = 'schedule',
  LaunchScreen = 'launchScreen',
  LoginScreen = 'login',
  SuccessScreen = 'success',
  ErrorScreen = 'error',
  SearchScreen = 'search',
  RegisterProfessionalScreen = 'registerProfessional',
  ForgotPasswordScreen = 'forgotPassword',
  EditPerfilScreen = 'editPerfil',
  FinishScheduleScreen = 'finishSchedule',
  EditScheduleScreen = 'editSchedule',
  NewScheduleScreen = 'newSchedule',
  ScheduleSignatureScreen = 'scheduleSignature',
  SignatureScreen = 'signatureScreen',
  ConfirmScheduleScreen = 'confirmSchedule',
  UploadScheduleImageScreen = 'uploadScheduleImage',
  ConfirmImageRequestScreen = 'confirmImageRequest',
  HomeScreen = 'home',
  DocumentFirstAccessScreen = 'documentFirstAccess',
  PendingDocumentsScreen = 'pendingDocuments',
  WaitingDocsApprovementScreen = 'waitingDocsApprovement',
  UploadDocumentsScreen = 'uploadDocuments',
  DocumentFullScreen = 'documentFullScreen'
}
